### ISSUE TITLE
V0.9.5 brick

### ISSUE THREAD

**Issue by nihaopaul** [SmartArduino/WiFiMCU#3]
tried the updated firmware, drivers and bootloader, after flashing the V0.9.5 but now have a dead product. broke out the jlink for following https://fineshang.gitbooks.io/wifimcu-based-on-emw3165-user-manual/content/chapter2_7.html but am unable to connect to the device .. or jlink complains that no device is found, any pointers? i wired up the clk and io line with gnd and vref going into 3.3.

**Comment by SmartArduino** [comment]
Hi,nihaopaul
The mcu is stm32f411ce. Have you tried another programming tool? The swd interface(D5/D6) is connected directely to mcu gpio(https://github.com/SmartArduino/WiFiMCU/blob/master/Document/WiFiMCU_SCH.pdf).
 it's not common that swd tools could not communicate with mcu. 

We use  SEGGER J-Flash 5.00i to flash the WiFiMCU as the following settings:(the mcu type stm32f411ve is choosed as there is no options for stm32f411ce)
![image](https://cloud.githubusercontent.com/assets/7382504/9959359/f529cd92-5e45-11e5-893f-bbcc26cb0eaa.png)

Please feel free to email me(yangping@doit.am) if the problem is unsoled.

Best Regards,
doit_yp

**Comment by nihaopaul** [comment]
thanks! going to close this with a few notes as i run on OSX and how i solved it for me:
first, this needs to update a little: 
https://fineshang.gitbooks.io/wifimcu-based-on-emw3165-user-manual/content/chapter2_7.html

a little schema could help for people and the j-link.
![wifimcu-jtag](https://cloud.githubusercontent.com/assets/519051/10010493/cb3f36b2-611e-11e5-9470-34d7b4d7498f.png)

then, under the command line this worked for me:
start the jlinkexe on osx with:
`JLinkExe -if SWD -device STM32f411VE`
then run the following commands (update to latest release, but keep the order)

```
r
erase
r
loadbin BCM43362-5.90.230.12.bin, 0x00002000
loadbin Bootloader_V1.0.bin, 0x8000000
loadbin WiFiMCU_Firmware_Integer_V0.9.5_20150905.bin, 0x800C000
SWOFlush
g
```

<img width="278" alt="screen shot 2015-09-22 at 3 20 23 pm" src="https://cloud.githubusercontent.com/assets/519051/10012775/8c73433c-613d-11e5-86b4-cbefd4f98f9b.png">

**Comment by nihaopaul** [comment]
the flash was successful and verified, but still is not accessible over usb, have i done something wrong?

**Comment by nihaopaul** [comment]
went back to 20150824 and it works again! only thing i done different was erase the device, will try the latest one after lunch again

**Comment by nihaopaul** [comment]
confirmed, V0.9.5 does not work, i had done a erase this time but still not working, will go back to 20150824

**Comment by nihaopaul** [comment]
i lied! it does work! but the order needs to be: BCM43362-5.90.230.12.bin, bootloader, firmware
